production: &production
  :url: <%= ENV["REDIS_URL"] %>
  :password: <%= ENV["REDIS_PASSWORD"] %>
  :timeout: 1
development: &development
  :url: <%= ENV["REDIS_URL"] %>
  :timeout: 1
  :inline: true
test: *development
